# Generated by Django 4.2.7 on 2025-08-14 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sell', '賣出'), ('buy', '收購')], max_length=4, verbose_name='交易類型')),
                ('n8_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='N8幣數量')),
                ('twd_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='台幣金額')),
                ('quick_reply', models.BooleanField(default=True, verbose_name='客戶訊息是否有在三分鐘內回覆')),
                ('no_reply_reason', models.TextField(blank=True, verbose_name='未快速回覆原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('cs_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='客服')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '交易記錄',
                'verbose_name_plural': '交易記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
