# Generated by Django 4.2.7 on 2025-08-14 21:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kyc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_account', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='只能填入數字', regex='^\\d+$')], verbose_name='驗證帳戶')),
                ('file', models.FileField(upload_to=kyc.models.kyc_upload_path, verbose_name='檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to='customers.customer', verbose_name='客戶')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_uploads', to=settings.AUTH_USER_MODEL, verbose_name='上傳客服')),
            ],
            options={
                'verbose_name': 'KYC 記錄',
                'verbose_name_plural': 'KYC 記錄',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
