# Generated by Django 4.2.7 on 2025-08-15 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycrecord_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='file_description',
            field=models.TextField(blank=True, help_text='對此檔案的說明或備註', verbose_name='檔案說明'),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='bank_code',
            field=models.CharField(blank=True, help_text='請填入3位數字的銀行代碼（選填）', max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='請填入3位數字的銀行代碼', regex='^\\d{3}$')], verbose_name='銀行代碼'),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='verification_account',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='只能填入數字', regex='^\\d+$')], verbose_name='驗證帳戶'),
        ),
    ]
