# Generated by Django 4.2.7 on 2025-08-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('line_nickname', models.CharField(blank=True, max_length=100, verbose_name='Line 暱稱')),
                ('n8_nickname', models.CharField(blank=True, max_length=100, verbose_name='N8 暱稱')),
                ('n8_phone', models.CharField(blank=True, max_length=20, verbose_name='N8 電話')),
                ('n8_email', models.EmailField(blank=True, max_length=254, verbose_name='N8 信箱')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('verified_accounts', models.TextField(blank=True, verbose_name='驗證過的帳戶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'ordering': ['-updated_at'],
            },
        ),
    ]
