# Generated by Django 4.2.7 on 2025-08-15 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='bank_code',
            field=models.CharField(default=0, help_text='請填入3位數字的銀行代碼', max_length=3, validators=[django.core.validators.RegexValidator(message='請填入3位數字的銀行代碼', regex='^\\d{3}$')], verbose_name='銀行代碼'),
            preserve_default=False,
        ),
    ]
