# Generated by refactor script
from django.db import migrations, models
import django.core.validators
import kyc.models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kycrecord_file_description_alter_kycrecord_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrecord',
            name='file',
            field=models.FileField(blank=True, help_text='支援圖片和影片檔案，檔案大小不超過100MB（選填）', null=True, upload_to=kyc.models.kyc_upload_path, verbose_name='檔案'),
        ),
    ]
