# Generated by Django 4.2.7 on 2025-08-16 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_kycrecord_file_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrecord',
            name='file_description',
            field=models.TextField(blank=True, help_text='對此檔案的說明或備註（選填）', verbose_name='檔案說明'),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='verification_account',
            field=models.CharField(blank=True, help_text='請填入數字帳號（選填）', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='只能填入數字', regex='^\\d+$')], verbose_name='驗證帳戶'),
        ),
    ]
